// Generated by apps/web/scripts/sync-design-assets.ts. Do not edit manually.

export interface DesignAsset {
  readonly id: string
  readonly sourceFile: string
  readonly alt: string
  readonly width: number
  readonly height: number
  readonly aspectRatio: number
  readonly blurDataUrl: string
  readonly src: string
  readonly avifSrc: string
  readonly cardSrc: string
  readonly heroSrc: string
}

export const designAssets = {
  "war_ticket_alerts_updates": [
    {
      "id": "war_ticket_alerts_updates-1",
      "sourceFile": "Design/war_ticket_alerts_updates/code.html",
      "alt": "Alerts Updates visual 1",
      "width": 512,
      "height": 512,
      "aspectRatio": 1,
      "blurDataUrl": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQABAABIB0JYwCw7DcPM8XRgAA/vLoaEXHscva7GEOEb7py/2iqNxfPPyVu4QFMFQzCH29Dff+FIAA",
      "src": "/images/design/war_ticket_alerts_updates/alerts_updates-01.webp",
      "avifSrc": "/images/design/war_ticket_alerts_updates/alerts_updates-01.avif",
      "cardSrc": "/images/design/war_ticket_alerts_updates/alerts_updates-01-card.webp",
      "heroSrc": "/images/design/war_ticket_alerts_updates/alerts_updates-01-hero.webp"
    }
  ],
  "war_ticket_community_live_status": [
    {
      "id": "war_ticket_community_live_status-1",
      "sourceFile": "Design/war_ticket_community_live_status/code.html",
      "alt": "Community Live Status visual 1",
      "width": 512,
      "height": 512,
      "aspectRatio": 1,
      "blurDataUrl": "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAADQAQCdASoQABAABIB0JaQAAudk9f6lgAD+8qulb4dYc2oEgPpAAA==",
      "src": "/images/design/war_ticket_community_live_status/community_live_status-01.webp",
      "avifSrc": "/images/design/war_ticket_community_live_status/community_live_status-01.avif",
      "cardSrc": "/images/design/war_ticket_community_live_status/community_live_status-01-card.webp",
      "heroSrc": "/images/design/war_ticket_community_live_status/community_live_status-01-hero.webp"
    },
    {
      "id": "war_ticket_community_live_status-2",
      "sourceFile": "Design/war_ticket_community_live_status/code.html",
      "alt": "Community Live Status visual 2",
      "width": 286,
      "height": 512,
      "aspectRatio": 0.5586,
      "blurDataUrl": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAwBACdASoQAB0APyl8tVIuJ6UisAgBwCUJbACdACK4TM9BWUZLrkgypQAA/ujfR8sq1mMgPuyka6E8PL3ebDZTXlhGzdEngCHrvtguXO0ZjbMQTYnc7SiJbpvl5ifxOhdJyoRiQLEWNBL6lqs9trKcsCgS0AAA",
      "src": "/images/design/war_ticket_community_live_status/community_live_status-02.webp",
      "avifSrc": "/images/design/war_ticket_community_live_status/community_live_status-02.avif",
      "cardSrc": "/images/design/war_ticket_community_live_status/community_live_status-02-card.webp",
      "heroSrc": "/images/design/war_ticket_community_live_status/community_live_status-02-hero.webp"
    },
    {
      "id": "war_ticket_community_live_status-3",
      "sourceFile": "Design/war_ticket_community_live_status/code.html",
      "alt": "Community Live Status visual 3",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoQAAkABIB0JZQAAqG5h3gAAP7uwu3zLGaNmNj7l5Kdkx0zC14xlkQyANzDg+8d3xndxaNE/px2jgAA",
      "src": "/images/design/war_ticket_community_live_status/community_live_status-03.webp",
      "avifSrc": "/images/design/war_ticket_community_live_status/community_live_status-03.avif",
      "cardSrc": "/images/design/war_ticket_community_live_status/community_live_status-03-card.webp",
      "heroSrc": "/images/design/war_ticket_community_live_status/community_live_status-03-hero.webp"
    }
  ],
  "war_ticket_concert_discovery": [
    {
      "id": "war_ticket_concert_discovery-1",
      "sourceFile": "Design/war_ticket_concert_discovery/code.html",
      "alt": "Concert Discovery visual 1",
      "width": 512,
      "height": 512,
      "aspectRatio": 1,
      "blurDataUrl": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQABAABIB0JagCdAEfaUFXqPIAAP7sCXcqlWYRReGzj/5x456RyQnhgc/HytgGgVuMmpVXQNjtWP78Yiu2j2C5GXwg9eaoinlFD6gBRHAAAA==",
      "src": "/images/design/war_ticket_concert_discovery/concert_discovery-01.webp",
      "avifSrc": "/images/design/war_ticket_concert_discovery/concert_discovery-01.avif",
      "cardSrc": "/images/design/war_ticket_concert_discovery/concert_discovery-01-card.webp",
      "heroSrc": "/images/design/war_ticket_concert_discovery/concert_discovery-01-hero.webp"
    }
  ],
  "war_ticket_e_ticket_confirmation": [
    {
      "id": "war_ticket_e_ticket_confirmation-1",
      "sourceFile": "Design/war_ticket_e_ticket_confirmation/code.html",
      "alt": "E Ticket Confirmation visual 1",
      "width": 512,
      "height": 512,
      "aspectRatio": 1,
      "blurDataUrl": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQABAABIB0JYwAAusoJTlkAAD+8rHQSeS8n+JVHxZ6+7XFLz4akwdk42DRmzc9zCtNq0rRM5Z4p+78KIAAAA==",
      "src": "/images/design/war_ticket_e_ticket_confirmation/e_ticket_confirmation-01.webp",
      "avifSrc": "/images/design/war_ticket_e_ticket_confirmation/e_ticket_confirmation-01.avif",
      "cardSrc": "/images/design/war_ticket_e_ticket_confirmation/e_ticket_confirmation-01-card.webp",
      "heroSrc": "/images/design/war_ticket_e_ticket_confirmation/e_ticket_confirmation-01-hero.webp"
    },
    {
      "id": "war_ticket_e_ticket_confirmation-2",
      "sourceFile": "Design/war_ticket_e_ticket_confirmation/code.html",
      "alt": "E Ticket Confirmation visual 2",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAQCdASoQAAkABIB0JZQAAm3x0SQAAP7u50q7XYbNlbW22M6HHgaegflwUqnQ1E6KsK7Y7KRq31jOWgAAAA==",
      "src": "/images/design/war_ticket_e_ticket_confirmation/e_ticket_confirmation-02.webp",
      "avifSrc": "/images/design/war_ticket_e_ticket_confirmation/e_ticket_confirmation-02.avif",
      "cardSrc": "/images/design/war_ticket_e_ticket_confirmation/e_ticket_confirmation-02-card.webp",
      "heroSrc": "/images/design/war_ticket_e_ticket_confirmation/e_ticket_confirmation-02-hero.webp"
    },
    {
      "id": "war_ticket_e_ticket_confirmation-3",
      "sourceFile": "Design/war_ticket_e_ticket_confirmation/code.html",
      "alt": "E Ticket Confirmation visual 3",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoQAAkABIB0JaQAAqH2CyS8AAD+83t9B7ZaQsQLAcRYTj+5dqIruxgAAAA=",
      "src": "/images/design/war_ticket_e_ticket_confirmation/e_ticket_confirmation-03.webp",
      "avifSrc": "/images/design/war_ticket_e_ticket_confirmation/e_ticket_confirmation-03.avif",
      "cardSrc": "/images/design/war_ticket_e_ticket_confirmation/e_ticket_confirmation-03-card.webp",
      "heroSrc": "/images/design/war_ticket_e_ticket_confirmation/e_ticket_confirmation-03-hero.webp"
    }
  ],
  "war_ticket_elite_membership_program": [
    {
      "id": "war_ticket_elite_membership_program-1",
      "sourceFile": "Design/war_ticket_elite_membership_program/code.html",
      "alt": "Elite Membership Program visual 1",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoQAAkABIB0JQBOgCBsPl23gAD+8rDV8mjYeL7ZYdQbq63YlDrfbinoNAAAAA==",
      "src": "/images/design/war_ticket_elite_membership_program/elite_membership_program-01.webp",
      "avifSrc": "/images/design/war_ticket_elite_membership_program/elite_membership_program-01.avif",
      "cardSrc": "/images/design/war_ticket_elite_membership_program/elite_membership_program-01-card.webp",
      "heroSrc": "/images/design/war_ticket_elite_membership_program/elite_membership_program-01-hero.webp"
    },
    {
      "id": "war_ticket_elite_membership_program-2",
      "sourceFile": "Design/war_ticket_elite_membership_program/code.html",
      "alt": "Elite Membership Program visual 2",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoQAAkABIB0JZQAAsWOd9SAAP7vW39MpGIr5ELG7nX5H3vJx7wUutoZpLU8DbELrwAAAA==",
      "src": "/images/design/war_ticket_elite_membership_program/elite_membership_program-02.webp",
      "avifSrc": "/images/design/war_ticket_elite_membership_program/elite_membership_program-02.avif",
      "cardSrc": "/images/design/war_ticket_elite_membership_program/elite_membership_program-02-card.webp",
      "heroSrc": "/images/design/war_ticket_elite_membership_program/elite_membership_program-02-hero.webp"
    }
  ],
  "war_ticket_elite_vanguard_lounge": [
    {
      "id": "war_ticket_elite_vanguard_lounge-1",
      "sourceFile": "Design/war_ticket_elite_vanguard_lounge/code.html",
      "alt": "Elite Vanguard Lounge visual 1",
      "width": 512,
      "height": 512,
      "aspectRatio": 1,
      "blurDataUrl": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoQABAABIB0JZwAAuSDfNeDAAD+8Mv9lYzBCFfs+e08VVobtd+E1SwT7kV4AA==",
      "src": "/images/design/war_ticket_elite_vanguard_lounge/elite_vanguard_lounge-01.webp",
      "avifSrc": "/images/design/war_ticket_elite_vanguard_lounge/elite_vanguard_lounge-01.avif",
      "cardSrc": "/images/design/war_ticket_elite_vanguard_lounge/elite_vanguard_lounge-01-card.webp",
      "heroSrc": "/images/design/war_ticket_elite_vanguard_lounge/elite_vanguard_lounge-01-hero.webp"
    },
    {
      "id": "war_ticket_elite_vanguard_lounge-2",
      "sourceFile": "Design/war_ticket_elite_vanguard_lounge/code.html",
      "alt": "Elite Vanguard Lounge visual 2",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoQAAkABIB0JZgCdAEMtdtKwAD+7Qmp9MG/8lqnVzkMoaFbNZ2XejnTpyfQNEVZa6ZylG28LAAAAA==",
      "src": "/images/design/war_ticket_elite_vanguard_lounge/elite_vanguard_lounge-02.webp",
      "avifSrc": "/images/design/war_ticket_elite_vanguard_lounge/elite_vanguard_lounge-02.avif",
      "cardSrc": "/images/design/war_ticket_elite_vanguard_lounge/elite_vanguard_lounge-02-card.webp",
      "heroSrc": "/images/design/war_ticket_elite_vanguard_lounge/elite_vanguard_lounge-02-hero.webp"
    },
    {
      "id": "war_ticket_elite_vanguard_lounge-3",
      "sourceFile": "Design/war_ticket_elite_vanguard_lounge/code.html",
      "alt": "Elite Vanguard Lounge visual 3",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoQAAkABIB0JQBYdh9BgH6kAAD+8YCDb0LFVJcErOm9vycEHln0i3cLkpGR4EcRZPMAAA==",
      "src": "/images/design/war_ticket_elite_vanguard_lounge/elite_vanguard_lounge-03.webp",
      "avifSrc": "/images/design/war_ticket_elite_vanguard_lounge/elite_vanguard_lounge-03.avif",
      "cardSrc": "/images/design/war_ticket_elite_vanguard_lounge/elite_vanguard_lounge-03-card.webp",
      "heroSrc": "/images/design/war_ticket_elite_vanguard_lounge/elite_vanguard_lounge-03-hero.webp"
    }
  ],
  "war_ticket_event_setup_inventory": [
    {
      "id": "war_ticket_event_setup_inventory-1",
      "sourceFile": "Design/war_ticket_event_setup_inventory/code.html",
      "alt": "Event Setup Inventory visual 1",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAkABIB0JQAAVCx4c60PAAD+7x3DszByye6rsxlcXljInxsjfcb2pk2gr6xoWCe+Ye4ODpw1kPprcbYwAAAA",
      "src": "/images/design/war_ticket_event_setup_inventory/event_setup_inventory-01.webp",
      "avifSrc": "/images/design/war_ticket_event_setup_inventory/event_setup_inventory-01.avif",
      "cardSrc": "/images/design/war_ticket_event_setup_inventory/event_setup_inventory-01-card.webp",
      "heroSrc": "/images/design/war_ticket_event_setup_inventory/event_setup_inventory-01-hero.webp"
    }
  ],
  "war_ticket_express_checkout": [
    {
      "id": "war_ticket_express_checkout-1",
      "sourceFile": "Design/war_ticket_express_checkout/code.html",
      "alt": "Express Checkout visual 1",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAkABIB0JYgCdADw2YnyZgAA/vL735y5/bIPn9xzKRwF/i85jIJUpmXN/w+6KZBELRg0p6pno2MopLuAAA==",
      "src": "/images/design/war_ticket_express_checkout/express_checkout-01.webp",
      "avifSrc": "/images/design/war_ticket_express_checkout/express_checkout-01.avif",
      "cardSrc": "/images/design/war_ticket_express_checkout/express_checkout-01-card.webp",
      "heroSrc": "/images/design/war_ticket_express_checkout/express_checkout-01-hero.webp"
    }
  ],
  "war_ticket_help_center": [
    {
      "id": "war_ticket_help_center-1",
      "sourceFile": "Design/war_ticket_help_center/code.html",
      "alt": "Help Center visual 1",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADwAQCdASoQAAkABIB0JZQCdAEffftWMAAA/uzD9IqEIdL5lQUxXmcyt8MAAA==",
      "src": "/images/design/war_ticket_help_center/help_center-01.webp",
      "avifSrc": "/images/design/war_ticket_help_center/help_center-01.avif",
      "cardSrc": "/images/design/war_ticket_help_center/help_center-01-card.webp",
      "heroSrc": "/images/design/war_ticket_help_center/help_center-01-hero.webp"
    }
  ],
  "war_ticket_high_stakes_ticketing_ecosystem": [
    {
      "id": "war_ticket_high_stakes_ticketing_ecosystem-1",
      "sourceFile": "Design/war_ticket_high_stakes_ticketing_ecosystem/code.html",
      "alt": "High Stakes Ticketing Ecosystem visual 1",
      "width": 512,
      "height": 286,
      "aspectRatio": 1.7902,
      "blurDataUrl": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoQAAkABIB0JQBYdh3rvtwAAP7vYxg1lmwgHIDcpO/8NDbqJMWs3TjaZdbWvotqZIH1AAAA",
      "src": "/images/design/war_ticket_high_stakes_ticketing_ecosystem/high_stakes_ticketing_ecosystem-01.webp",
      "avifSrc": "/images/design/war_ticket_high_stakes_ticketing_ecosystem/high_stakes_ticketing_ecosystem-01.avif",
      "cardSrc": "/images/design/war_ticket_high_stakes_ticketing_ecosystem/high_stakes_ticketing_ecosystem-01-card.webp",
      "heroSrc": "/images/design/war_ticket_high_stakes_ticketing_ecosystem/high_stakes_ticketing_ecosystem-01-hero.webp"
    },
    {
      "id": "war_ticket_high_stakes_ticketing_ecosystem-2",
      "sourceFile": "Design/war_ticket_high_stakes_ticketing_ecosystem/code.html",
      "alt": "High Stakes Ticketing Ecosystem visual 2",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoQAAkABIB0JYwC7AD1d0+MgAD+8N7z78xWTQjKKtMWFoUrU9w9/GoU46UuRv0AAAA=",
      "src": "/images/design/war_ticket_high_stakes_ticketing_ecosystem/high_stakes_ticketing_ecosystem-02.webp",
      "avifSrc": "/images/design/war_ticket_high_stakes_ticketing_ecosystem/high_stakes_ticketing_ecosystem-02.avif",
      "cardSrc": "/images/design/war_ticket_high_stakes_ticketing_ecosystem/high_stakes_ticketing_ecosystem-02-card.webp",
      "heroSrc": "/images/design/war_ticket_high_stakes_ticketing_ecosystem/high_stakes_ticketing_ecosystem-02-hero.webp"
    },
    {
      "id": "war_ticket_high_stakes_ticketing_ecosystem-3",
      "sourceFile": "Design/war_ticket_high_stakes_ticketing_ecosystem/code.html",
      "alt": "High Stakes Ticketing Ecosystem visual 3",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAkABIB0JQBOgCIG1+ve5AAA/uoQi0zPe1ZrJqPJnZKwLD93iQih+3SLbACye98sHA1iZbPW53bIKAyOYqlQAAA=",
      "src": "/images/design/war_ticket_high_stakes_ticketing_ecosystem/high_stakes_ticketing_ecosystem-03.webp",
      "avifSrc": "/images/design/war_ticket_high_stakes_ticketing_ecosystem/high_stakes_ticketing_ecosystem-03.avif",
      "cardSrc": "/images/design/war_ticket_high_stakes_ticketing_ecosystem/high_stakes_ticketing_ecosystem-03-card.webp",
      "heroSrc": "/images/design/war_ticket_high_stakes_ticketing_ecosystem/high_stakes_ticketing_ecosystem-03-hero.webp"
    }
  ],
  "war_ticket_landing_page": [
    {
      "id": "war_ticket_landing_page-1",
      "sourceFile": "Design/war_ticket_landing_page/code.html",
      "alt": "Landing Page visual 1",
      "width": 512,
      "height": 286,
      "aspectRatio": 1.7902,
      "blurDataUrl": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoQAAkABIB0JQBYdh3rvtwAAP7vYxg1lmwgHIDcpO/8NDbqJMWs3TjaZdbWvotqZIH1AAAA",
      "src": "/images/design/war_ticket_landing_page/landing_page-01.webp",
      "avifSrc": "/images/design/war_ticket_landing_page/landing_page-01.avif",
      "cardSrc": "/images/design/war_ticket_landing_page/landing_page-01-card.webp",
      "heroSrc": "/images/design/war_ticket_landing_page/landing_page-01-hero.webp"
    },
    {
      "id": "war_ticket_landing_page-2",
      "sourceFile": "Design/war_ticket_landing_page/code.html",
      "alt": "Landing Page visual 2",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoQAAkABIB0JYwC7AD1d0+MgAD+8N7z78xWTQjKKtMWFoUrU9w9/GoU46UuRv0AAAA=",
      "src": "/images/design/war_ticket_landing_page/landing_page-02.webp",
      "avifSrc": "/images/design/war_ticket_landing_page/landing_page-02.avif",
      "cardSrc": "/images/design/war_ticket_landing_page/landing_page-02-card.webp",
      "heroSrc": "/images/design/war_ticket_landing_page/landing_page-02-hero.webp"
    },
    {
      "id": "war_ticket_landing_page-3",
      "sourceFile": "Design/war_ticket_landing_page/code.html",
      "alt": "Landing Page visual 3",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAkABIB0JQBOgCIG1+ve5AAA/uoQi0zPe1ZrJqPJnZKwLD93iQih+3SLbACye98sHA1iZbPW53bIKAyOYqlQAAA=",
      "src": "/images/design/war_ticket_landing_page/landing_page-03.webp",
      "avifSrc": "/images/design/war_ticket_landing_page/landing_page-03.avif",
      "cardSrc": "/images/design/war_ticket_landing_page/landing_page-03-card.webp",
      "heroSrc": "/images/design/war_ticket_landing_page/landing_page-03-hero.webp"
    }
  ],
  "war_ticket_order_history": [
    {
      "id": "war_ticket_order_history-1",
      "sourceFile": "Design/war_ticket_order_history/code.html",
      "alt": "Order History visual 1",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoQAAkABIB0JYwCw7EfvxMiu4wAAP7vYkJPv2JtMQ0LC6M98Ih1TtJBMp59tgHXc05QAAAA",
      "src": "/images/design/war_ticket_order_history/order_history-01.webp",
      "avifSrc": "/images/design/war_ticket_order_history/order_history-01.avif",
      "cardSrc": "/images/design/war_ticket_order_history/order_history-01-card.webp",
      "heroSrc": "/images/design/war_ticket_order_history/order_history-01-hero.webp"
    },
    {
      "id": "war_ticket_order_history-2",
      "sourceFile": "Design/war_ticket_order_history/code.html",
      "alt": "Order History visual 2",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoQAAkABIB0JZQAArIe3ORAAP7ytJNsW7eG6fBhOPObAS9fz29wclSLAABpAAAA",
      "src": "/images/design/war_ticket_order_history/order_history-02.webp",
      "avifSrc": "/images/design/war_ticket_order_history/order_history-02.avif",
      "cardSrc": "/images/design/war_ticket_order_history/order_history-02-card.webp",
      "heroSrc": "/images/design/war_ticket_order_history/order_history-02-hero.webp"
    },
    {
      "id": "war_ticket_order_history-3",
      "sourceFile": "Design/war_ticket_order_history/code.html",
      "alt": "Order History visual 3",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoQAAkABIB0JZwAAueDQ7raAAD+8yBnkbpvk1ot64jBZtgHiuEXqXyOgQAAAA==",
      "src": "/images/design/war_ticket_order_history/order_history-03.webp",
      "avifSrc": "/images/design/war_ticket_order_history/order_history-03.avif",
      "cardSrc": "/images/design/war_ticket_order_history/order_history-03-card.webp",
      "heroSrc": "/images/design/war_ticket_order_history/order_history-03-hero.webp"
    },
    {
      "id": "war_ticket_order_history-4",
      "sourceFile": "Design/war_ticket_order_history/code.html",
      "alt": "Order History visual 4",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAQCdASoQAAkABIB0JZwAAgaAgQAA/u7pD/bBapX9Lgfm9MnjPM14xFXUMA/OWocHq3HEfu/qQqzq/2DZkAAA",
      "src": "/images/design/war_ticket_order_history/order_history-04.webp",
      "avifSrc": "/images/design/war_ticket_order_history/order_history-04.avif",
      "cardSrc": "/images/design/war_ticket_order_history/order_history-04-card.webp",
      "heroSrc": "/images/design/war_ticket_order_history/order_history-04-hero.webp"
    }
  ],
  "war_ticket_organizer_command_center": [
    {
      "id": "war_ticket_organizer_command_center-1",
      "sourceFile": "Design/war_ticket_organizer_command_center/code.html",
      "alt": "Organizer Command Center visual 1",
      "width": 512,
      "height": 512,
      "aspectRatio": 1,
      "blurDataUrl": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQABAABIB0JZwAAtz3pKFZgAD+8qoTT+dY5WoenyQxcCDcWGCHpAsoTqaBxEdl+WDnkxTdXofTAAAA",
      "src": "/images/design/war_ticket_organizer_command_center/organizer_command_center-01.webp",
      "avifSrc": "/images/design/war_ticket_organizer_command_center/organizer_command_center-01.avif",
      "cardSrc": "/images/design/war_ticket_organizer_command_center/organizer_command_center-01-card.webp",
      "heroSrc": "/images/design/war_ticket_organizer_command_center/organizer_command_center-01-hero.webp"
    }
  ],
  "war_ticket_organizer_reporting_center": [
    {
      "id": "war_ticket_organizer_reporting_center-1",
      "sourceFile": "Design/war_ticket_organizer_reporting_center/code.html",
      "alt": "Organizer Reporting Center visual 1",
      "width": 286,
      "height": 512,
      "aspectRatio": 0.5586,
      "blurDataUrl": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACwAwCdASoQAB0APyl8tVIuJ6UisAgBwCUJZQAAUoDhugWXiTIMCAD+44SOhrd4AoIvwURmmD/wjx7Pw4ewCLaWbNL0gyzGFLeyHo8Bq275ug938QS1jYVjWL3oUzOdzYGbv/hJQ7xcAA==",
      "src": "/images/design/war_ticket_organizer_reporting_center/organizer_reporting_center-01.webp",
      "avifSrc": "/images/design/war_ticket_organizer_reporting_center/organizer_reporting_center-01.avif",
      "cardSrc": "/images/design/war_ticket_organizer_reporting_center/organizer_reporting_center-01-card.webp",
      "heroSrc": "/images/design/war_ticket_organizer_reporting_center/organizer_reporting_center-01-hero.webp"
    }
  ],
  "war_ticket_organizer_wallet_settlements": [
    {
      "id": "war_ticket_organizer_wallet_settlements-1",
      "sourceFile": "Design/war_ticket_organizer_wallet_settlements/code.html",
      "alt": "Organizer Wallet Settlements visual 1",
      "width": 512,
      "height": 512,
      "aspectRatio": 1,
      "blurDataUrl": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoQABAABIB0JYwCsAD0fXAx8AAA/uv+gkxcjAtUQdCKY0UUNY4+NSODAeDO2Nn5zvGckt6IkiAAAA==",
      "src": "/images/design/war_ticket_organizer_wallet_settlements/organizer_wallet_settlements-01.webp",
      "avifSrc": "/images/design/war_ticket_organizer_wallet_settlements/organizer_wallet_settlements-01.avif",
      "cardSrc": "/images/design/war_ticket_organizer_wallet_settlements/organizer_wallet_settlements-01-card.webp",
      "heroSrc": "/images/design/war_ticket_organizer_wallet_settlements/organizer_wallet_settlements-01-hero.webp"
    }
  ],
  "war_ticket_partner_onboarding": [
    {
      "id": "war_ticket_partner_onboarding-1",
      "sourceFile": "Design/war_ticket_partner_onboarding/code.html",
      "alt": "Partner Onboarding visual 1",
      "width": 512,
      "height": 286,
      "aspectRatio": 1.7902,
      "blurDataUrl": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACQAQCdASoQAAkABIB0JZQAAuKgpIAA/vGAgkKDUKDh56r8ldvpoSVfEz7GXK2nJvwYsW5AAAA=",
      "src": "/images/design/war_ticket_partner_onboarding/partner_onboarding-01.webp",
      "avifSrc": "/images/design/war_ticket_partner_onboarding/partner_onboarding-01.avif",
      "cardSrc": "/images/design/war_ticket_partner_onboarding/partner_onboarding-01-card.webp",
      "heroSrc": "/images/design/war_ticket_partner_onboarding/partner_onboarding-01-hero.webp"
    },
    {
      "id": "war_ticket_partner_onboarding-2",
      "sourceFile": "Design/war_ticket_partner_onboarding/code.html",
      "alt": "Partner Onboarding visual 2",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoQAAkABIB0JZQAAq4JnXexgAD+72NPGYAAVwIesjj4u6fRQ1VRRMKqaXRh6/RdgQAAAA==",
      "src": "/images/design/war_ticket_partner_onboarding/partner_onboarding-02.webp",
      "avifSrc": "/images/design/war_ticket_partner_onboarding/partner_onboarding-02.avif",
      "cardSrc": "/images/design/war_ticket_partner_onboarding/partner_onboarding-02-card.webp",
      "heroSrc": "/images/design/war_ticket_partner_onboarding/partner_onboarding-02-hero.webp"
    }
  ],
  "war_ticket_platform_admin_dashboard": [
    {
      "id": "war_ticket_platform_admin_dashboard-1",
      "sourceFile": "Design/war_ticket_platform_admin_dashboard/code.html",
      "alt": "Platform Admin Dashboard visual 1",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoQAAkABIB0JZwAAsf3qqdqAAD+9DKoEoZ82p/Vw4zDSDuBGuwqKcWvSLoOAA==",
      "src": "/images/design/war_ticket_platform_admin_dashboard/platform_admin_dashboard-01.webp",
      "avifSrc": "/images/design/war_ticket_platform_admin_dashboard/platform_admin_dashboard-01.avif",
      "cardSrc": "/images/design/war_ticket_platform_admin_dashboard/platform_admin_dashboard-01-card.webp",
      "heroSrc": "/images/design/war_ticket_platform_admin_dashboard/platform_admin_dashboard-01-hero.webp"
    },
    {
      "id": "war_ticket_platform_admin_dashboard-2",
      "sourceFile": "Design/war_ticket_platform_admin_dashboard/code.html",
      "alt": "Platform Admin Dashboard visual 2",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAQCdASoQAAkABIB0JZQCw7EPSqhGhAAA/uyLTsh0UqAtjLyS6WAlviv/AqseAAA=",
      "src": "/images/design/war_ticket_platform_admin_dashboard/platform_admin_dashboard-02.webp",
      "avifSrc": "/images/design/war_ticket_platform_admin_dashboard/platform_admin_dashboard-02.avif",
      "cardSrc": "/images/design/war_ticket_platform_admin_dashboard/platform_admin_dashboard-02-card.webp",
      "heroSrc": "/images/design/war_ticket_platform_admin_dashboard/platform_admin_dashboard-02-hero.webp"
    },
    {
      "id": "war_ticket_platform_admin_dashboard-3",
      "sourceFile": "Design/war_ticket_platform_admin_dashboard/code.html",
      "alt": "Platform Admin Dashboard visual 3",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACwAQCdASoQAAkABIB0JZwAAvqlVU+gAP7upgs9ecQkc+fjLEiNeg4TAAA=",
      "src": "/images/design/war_ticket_platform_admin_dashboard/platform_admin_dashboard-03.webp",
      "avifSrc": "/images/design/war_ticket_platform_admin_dashboard/platform_admin_dashboard-03.avif",
      "cardSrc": "/images/design/war_ticket_platform_admin_dashboard/platform_admin_dashboard-03-card.webp",
      "heroSrc": "/images/design/war_ticket_platform_admin_dashboard/platform_admin_dashboard-03-hero.webp"
    },
    {
      "id": "war_ticket_platform_admin_dashboard-4",
      "sourceFile": "Design/war_ticket_platform_admin_dashboard/code.html",
      "alt": "Platform Admin Dashboard visual 4",
      "width": 512,
      "height": 512,
      "aspectRatio": 1,
      "blurDataUrl": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQABAABIB0JZQAAq4Ic3dFAAD+9DLJvxUPcoJ9xpFDTOG3Cn0K9QUxQrpXVN6GfcTPRq6eGucQXUKAAAA=",
      "src": "/images/design/war_ticket_platform_admin_dashboard/platform_admin_dashboard-04.webp",
      "avifSrc": "/images/design/war_ticket_platform_admin_dashboard/platform_admin_dashboard-04.avif",
      "cardSrc": "/images/design/war_ticket_platform_admin_dashboard/platform_admin_dashboard-04-card.webp",
      "heroSrc": "/images/design/war_ticket_platform_admin_dashboard/platform_admin_dashboard-04-hero.webp"
    }
  ],
  "war_ticket_profile_settings": [
    {
      "id": "war_ticket_profile_settings-1",
      "sourceFile": "Design/war_ticket_profile_settings/code.html",
      "alt": "Profile Settings visual 1",
      "width": 512,
      "height": 512,
      "aspectRatio": 1,
      "blurDataUrl": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQABAABIB0JQAAU/m8pMH9//gAAP7qSD5OyrIbUrmCErW3piorkd0CTq/l0Lxg0KJLRiayc6haBu3kFXsUPSdlSrRF335LoVrGkrWw45pCYLBLwAA=",
      "src": "/images/design/war_ticket_profile_settings/profile_settings-01.webp",
      "avifSrc": "/images/design/war_ticket_profile_settings/profile_settings-01.avif",
      "cardSrc": "/images/design/war_ticket_profile_settings/profile_settings-01-card.webp",
      "heroSrc": "/images/design/war_ticket_profile_settings/profile_settings-01-hero.webp"
    },
    {
      "id": "war_ticket_profile_settings-2",
      "sourceFile": "Design/war_ticket_profile_settings/code.html",
      "alt": "Profile Settings visual 2",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoQAAkABIB0JaQAAuddNQfgAP71eawLKr3NSB3X3tFC3xxydKAAAA==",
      "src": "/images/design/war_ticket_profile_settings/profile_settings-02.webp",
      "avifSrc": "/images/design/war_ticket_profile_settings/profile_settings-02.avif",
      "cardSrc": "/images/design/war_ticket_profile_settings/profile_settings-02-card.webp",
      "heroSrc": "/images/design/war_ticket_profile_settings/profile_settings-02-hero.webp"
    }
  ],
  "war_ticket_promos_exclusive_deals": [
    {
      "id": "war_ticket_promos_exclusive_deals-1",
      "sourceFile": "Design/war_ticket_promos_exclusive_deals/code.html",
      "alt": "Promos Exclusive Deals visual 1",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAAAwAQCdASoQAAkABIB0JZwAA3AA/vCI+1q90vsAMp/PVOtP8jVQ/gHqTW3qZYUAAAA=",
      "src": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-01.webp",
      "avifSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-01.avif",
      "cardSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-01-card.webp",
      "heroSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-01-hero.webp"
    },
    {
      "id": "war_ticket_promos_exclusive_deals-2",
      "sourceFile": "Design/war_ticket_promos_exclusive_deals/code.html",
      "alt": "Promos Exclusive Deals visual 2",
      "width": 512,
      "height": 286,
      "aspectRatio": 1.7902,
      "blurDataUrl": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoQAAkABIB0JZQAAp2zoc0AAP7w3RCDpQXvqHGvQcDo4tDbPbtRI43tCAA=",
      "src": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-02.webp",
      "avifSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-02.avif",
      "cardSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-02-card.webp",
      "heroSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-02-hero.webp"
    },
    {
      "id": "war_ticket_promos_exclusive_deals-3",
      "sourceFile": "Design/war_ticket_promos_exclusive_deals/code.html",
      "alt": "Promos Exclusive Deals visual 3",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoQAAkABIB0JZQCdAD7ALpRAAD+9DLHuVSHkp/iiNrguWXlJPecAAAA",
      "src": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-03.webp",
      "avifSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-03.avif",
      "cardSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-03-card.webp",
      "heroSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-03-hero.webp"
    },
    {
      "id": "war_ticket_promos_exclusive_deals-4",
      "sourceFile": "Design/war_ticket_promos_exclusive_deals/code.html",
      "alt": "Promos Exclusive Deals visual 4",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoQAAkABIB0JZQAApLheKQgAAD+8rQwzhWMYgvqf+dI2Ts6VEyVQEbQYxrxYIjgAoDA5IAA",
      "src": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-04.webp",
      "avifSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-04.avif",
      "cardSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-04-card.webp",
      "heroSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-04-hero.webp"
    },
    {
      "id": "war_ticket_promos_exclusive_deals-5",
      "sourceFile": "Design/war_ticket_promos_exclusive_deals/code.html",
      "alt": "Promos Exclusive Deals visual 5",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAAAQAgCdASoQAAkABIB0JZwAAxdV7mM8NM4AAP7usQ61xGkklORWfC5SuRRvKPVEBdqAAAAA",
      "src": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-05.webp",
      "avifSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-05.avif",
      "cardSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-05-card.webp",
      "heroSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-05-hero.webp"
    },
    {
      "id": "war_ticket_promos_exclusive_deals-6",
      "sourceFile": "Design/war_ticket_promos_exclusive_deals/code.html",
      "alt": "Promos Exclusive Deals visual 6",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAQCdASoQAAkABIB0JQBdgBVS2SgA/vQvmuZvxo0l3AO9Mxv3HMlu2a2bdlEtVQlHmCUi73l23i+o8Lf0r8c08AA=",
      "src": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-06.webp",
      "avifSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-06.avif",
      "cardSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-06-card.webp",
      "heroSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-06-hero.webp"
    },
    {
      "id": "war_ticket_promos_exclusive_deals-7",
      "sourceFile": "Design/war_ticket_promos_exclusive_deals/code.html",
      "alt": "Promos Exclusive Deals visual 7",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAAAwAQCdASoQAAkABIB0JZwAA3AA/vC2qQvKfyBQpyTriO1lisfQAA==",
      "src": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-07.webp",
      "avifSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-07.avif",
      "cardSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-07-card.webp",
      "heroSrc": "/images/design/war_ticket_promos_exclusive_deals/promos_exclusive_deals-07-hero.webp"
    }
  ],
  "war_ticket_seat_map_selection": [
    {
      "id": "war_ticket_seat_map_selection-1",
      "sourceFile": "Design/war_ticket_seat_map_selection/code.html",
      "alt": "Seat Map Selection visual 1",
      "width": 512,
      "height": 512,
      "aspectRatio": 1,
      "blurDataUrl": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoQABAABIB0JaQAAjp9kEAAAP7w36d6aE6vHuQihn5FperqzgvAQ8qyASWGPx7WO9zY4AAA",
      "src": "/images/design/war_ticket_seat_map_selection/seat_map_selection-01.webp",
      "avifSrc": "/images/design/war_ticket_seat_map_selection/seat_map_selection-01.avif",
      "cardSrc": "/images/design/war_ticket_seat_map_selection/seat_map_selection-01-card.webp",
      "heroSrc": "/images/design/war_ticket_seat_map_selection/seat_map_selection-01-hero.webp"
    }
  ],
  "war_ticket_seating_analytics": [
    {
      "id": "war_ticket_seating_analytics-1",
      "sourceFile": "Design/war_ticket_seating_analytics/code.html",
      "alt": "Seating Analytics visual 1",
      "width": 512,
      "height": 512,
      "aspectRatio": 1,
      "blurDataUrl": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQABAABIB0JZwAAohe9Ka8woAA/uv8uI4Rk+c69Ul4dJQeWUaAxUyibukmrrnfAfNJllun9W6CAAAA",
      "src": "/images/design/war_ticket_seating_analytics/seating_analytics-01.webp",
      "avifSrc": "/images/design/war_ticket_seating_analytics/seating_analytics-01.avif",
      "cardSrc": "/images/design/war_ticket_seating_analytics/seating_analytics-01-card.webp",
      "heroSrc": "/images/design/war_ticket_seating_analytics/seating_analytics-01-hero.webp"
    }
  ],
  "war_ticket_security_access_control": [
    {
      "id": "war_ticket_security_access_control-1",
      "sourceFile": "Design/war_ticket_security_access_control/code.html",
      "alt": "Security Access Control visual 1",
      "width": 512,
      "height": 512,
      "aspectRatio": 1,
      "blurDataUrl": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAQCdASoQABAABIB0JZQCw7EPAD2F6XgA/unFXM5PQTxsVlt4BIJMVEHwYDiYAAA=",
      "src": "/images/design/war_ticket_security_access_control/security_access_control-01.webp",
      "avifSrc": "/images/design/war_ticket_security_access_control/security_access_control-01.avif",
      "cardSrc": "/images/design/war_ticket_security_access_control/security_access_control-01-card.webp",
      "heroSrc": "/images/design/war_ticket_security_access_control/security_access_control-01-hero.webp"
    }
  ],
  "war_ticket_support_dispute_system": [
    {
      "id": "war_ticket_support_dispute_system-1",
      "sourceFile": "Design/war_ticket_support_dispute_system/code.html",
      "alt": "Support Dispute System visual 1",
      "width": 512,
      "height": 512,
      "aspectRatio": 1,
      "blurDataUrl": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQABAABIB0JQBOgB6QDwFG2wAA/vQyybVc07b0/Evr42DKEd5wewm7IInhzcOFWlF16+lPmxoLZr4UtaGTDq0AAAA=",
      "src": "/images/design/war_ticket_support_dispute_system/support_dispute_system-01.webp",
      "avifSrc": "/images/design/war_ticket_support_dispute_system/support_dispute_system-01.avif",
      "cardSrc": "/images/design/war_ticket_support_dispute_system/support_dispute_system-01-card.webp",
      "heroSrc": "/images/design/war_ticket_support_dispute_system/support_dispute_system-01-hero.webp"
    }
  ],
  "war_ticket_system_audit_log": [
    {
      "id": "war_ticket_system_audit_log-1",
      "sourceFile": "Design/war_ticket_system_audit_log/code.html",
      "alt": "System Audit Log visual 1",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAABQAQCdASoQAAkABIB0JaQABDOAAP7v44RpRIAA",
      "src": "/images/design/war_ticket_system_audit_log/system_audit_log-01.webp",
      "avifSrc": "/images/design/war_ticket_system_audit_log/system_audit_log-01.avif",
      "cardSrc": "/images/design/war_ticket_system_audit_log/system_audit_log-01-card.webp",
      "heroSrc": "/images/design/war_ticket_system_audit_log/system_audit_log-01-hero.webp"
    }
  ],
  "war_ticket_user_dashboard": [
    {
      "id": "war_ticket_user_dashboard-1",
      "sourceFile": "Design/war_ticket_user_dashboard/code.html",
      "alt": "User Dashboard visual 1",
      "width": 512,
      "height": 512,
      "aspectRatio": 1,
      "blurDataUrl": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoQABAABIB0JZwAAudgGEJj/AAA/vKhvcLkcRrP3hR1qOIfcoQx+2hCvf/yBbNtxQAAAA==",
      "src": "/images/design/war_ticket_user_dashboard/user_dashboard-01.webp",
      "avifSrc": "/images/design/war_ticket_user_dashboard/user_dashboard-01.avif",
      "cardSrc": "/images/design/war_ticket_user_dashboard/user_dashboard-01-card.webp",
      "heroSrc": "/images/design/war_ticket_user_dashboard/user_dashboard-01-hero.webp"
    },
    {
      "id": "war_ticket_user_dashboard-2",
      "sourceFile": "Design/war_ticket_user_dashboard/code.html",
      "alt": "User Dashboard visual 2",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoQAAkABIB0JZACdADGTGpeAAD+72G4GjrbfYtL/BX8DZBOqvGIWUUKEVHq79BHspQAAA==",
      "src": "/images/design/war_ticket_user_dashboard/user_dashboard-02.webp",
      "avifSrc": "/images/design/war_ticket_user_dashboard/user_dashboard-02.avif",
      "cardSrc": "/images/design/war_ticket_user_dashboard/user_dashboard-02-card.webp",
      "heroSrc": "/images/design/war_ticket_user_dashboard/user_dashboard-02-hero.webp"
    },
    {
      "id": "war_ticket_user_dashboard-3",
      "sourceFile": "Design/war_ticket_user_dashboard/code.html",
      "alt": "User Dashboard visual 3",
      "width": 512,
      "height": 286,
      "aspectRatio": 1.7902,
      "blurDataUrl": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACQAQCdASoQAAkABIB0JQBdgB4VGoAA/vMdejPB4kpNTV9mqhx83ivHhWhS6AAA",
      "src": "/images/design/war_ticket_user_dashboard/user_dashboard-03.webp",
      "avifSrc": "/images/design/war_ticket_user_dashboard/user_dashboard-03.avif",
      "cardSrc": "/images/design/war_ticket_user_dashboard/user_dashboard-03-card.webp",
      "heroSrc": "/images/design/war_ticket_user_dashboard/user_dashboard-03-hero.webp"
    },
    {
      "id": "war_ticket_user_dashboard-4",
      "sourceFile": "Design/war_ticket_user_dashboard/code.html",
      "alt": "User Dashboard visual 4",
      "width": 512,
      "height": 279,
      "aspectRatio": 1.8351,
      "blurDataUrl": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoQAAkABIB0JYwAApMfzHcYAP7y3NplrbWmk9UteIXeBLU+gkKb1xkhyAAAAA==",
      "src": "/images/design/war_ticket_user_dashboard/user_dashboard-04.webp",
      "avifSrc": "/images/design/war_ticket_user_dashboard/user_dashboard-04.avif",
      "cardSrc": "/images/design/war_ticket_user_dashboard/user_dashboard-04-card.webp",
      "heroSrc": "/images/design/war_ticket_user_dashboard/user_dashboard-04-hero.webp"
    }
  ]
} as const satisfies Record<string, readonly DesignAsset[]>

export type DesignAssetGroup = keyof typeof designAssets

export const designAssetByPath = Object.fromEntries(
  Object.values(designAssets).flat().flatMap((asset) => [asset.src, asset.avifSrc, asset.cardSrc, asset.heroSrc].map((path) => [path, asset])),
) as Readonly<Record<string, DesignAsset>>

export function getDesignAsset(group: DesignAssetGroup, index = 0): DesignAsset {
  const asset = designAssets[group][index] as DesignAsset | undefined
  if (!asset) throw new Error(`Missing Design asset: ${group}[${index}]`)
  return asset
}
